name: CI


on:
  workflow_dispatch:
  push:
    branches: [master, dev]


jobs:
  windows-build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
        shared: [[ON, DLL], [OFF, ""]]

    steps:
    - uses: actions/checkout@v4

    - name: Enable NMake
      uses: ilammy/msvc-dev-cmd@v1.13.0

    - name: Build
      run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} -DBUILD_SHARED_LIBS=${{ matrix.shared[0] }} -G "NMake Makefiles" ..
          nmake install

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.configuration }}${{ matrix.shared[1] }}_Windows
        path: build/install-dir
      

  linux-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
        shared: [[ON, DLL], [OFF, ""]]

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
            mkdir build
            cd build
            cmake -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} -DBUILD_SHARED_LIBS=${{ matrix.shared[0] }} ..
            make install -j $(nproc)

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.configuration }}${{ matrix.shared[1] }}_Linux
          path: build/install-dir
  

  windows-tests:
    runs-on: windows-latest
    needs: [windows-build]
    strategy:
      matrix:
        configuration: [Debug, Release]
        shared: [[ON, DLL], [OFF, ""]]

    steps: 
    - uses: actions/checkout@v4
   
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@main
    
    - name: Enable NMake
      uses: ilammy/msvc-dev-cmd@v1.13.0

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: ${{ matrix.configuration }}${{ matrix.shared[1] }}_Windows
        path: ThreadPool

    - name: Get Google Tests
      uses: LazyPanda07/get-gtest@v1
      with:
        install-path: Tests/gtest
        build-type: ${{ matrix.configuration }}
        
    - name: Tests
      working-directory: ${{ github.workspace }}\Tests
      run: |
          msbuild /p:Configuration=${{ matrix.configuration }} /p:Platform=x64
          .\bin\${{ matrix.configuration }}-x64\Tests\Tests.exe

  
  linux-tests:
    runs-on: ubuntu-latest
    needs: [linux-build]
    strategy:
      matrix:
        configuration: [Debug, Release]
        shared: [[ON, DLL], [OFF, ""]]

    steps: 
    - uses: actions/checkout@v4

    - name: Get Google Tests
      uses: LazyPanda07/get-gtest@v1
      with:
        install-path: Tests/gtest

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: ${{ matrix.configuration }}${{ matrix.shared[1] }}_Linux
        path: ThreadPool
        
    - name: Tests
      working-directory: ${{ github.workspace }}/Tests
      run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make install -j $(nproc)
          cd ../build/
          export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:$(pwd)
          ./Tests
  
      
  memory-leak-tests:
    needs: [linux-build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
        shared: [[ON, DLL], [OFF, ""]]

    steps:
    - uses: actions/checkout@v4

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: ${{ matrix.configuration }}${{ matrix.shared[1] }}_Linux
        path: ThreadPool

    - name: Get Google Tests
      uses: LazyPanda07/get-gtest@v1
      with:
        install-path: Tests/gtest

    - name: Build tests
      working-directory: ${{ github.workspace }}/Tests
      run: |
          mkdir build
          cd build 
          cmake -DCMAKE_BUILD_TYPE=Release -DVALGRIND=ON ..
          make install -j $(nproc)

    - name: Memory leak test
      uses: LazyPanda07/check-memory-leaks@v1
      with:
        path: Tests/build/bin
        name: Tests
        pre-execute: export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:$(pwd)


  publish:
    needs: [windows-tests, linux-tests, memory-leak-tests]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: LazyPanda07/extract-current-branch@master
    
    - name: Setup release version variable
      shell: pwsh
      run: echo "VERSION=$($($($(Select-String -Path .\src\ThreadPool.cpp -Pattern version) -split '( = )')[3].TrimEnd(';')).Trim('\"'))" >> $Env:GITHUB_ENV

    - name: Print version
      run: echo ${{ env.VERSION }}

    - name: Download artifacts
      if: ${{ env.CURRENT_BRANCH == 'master' }}
      uses: actions/download-artifact@v4
      
    - name: Setup Windows build list
      run: echo "WINDOWS_BUILD_LIST="$(ls | grep Windows)"" >> ${GITHUB_ENV}
      
    - name: Create Windows zip
      if: ${{ env.CURRENT_BRANCH == 'master' }}
      run: zip -r windows.zip ${{ env.WINDOWS_BUILD_LIST }}

    - name: Create Linux zip
      if: ${{ env.CURRENT_BRANCH == 'master' }}
      run: zip -r linux.zip Release_Linux ReleaseDLL_Linux

    - name: Publish Windows
      if: ${{ env.CURRENT_BRANCH == 'master' }}
      uses: svenstaro/upload-release-action@master
      with:
        tag: v${{ env.VERSION }}
        file: windows.zip

    - name: Publish Linux
      if: ${{ env.CURRENT_BRANCH == 'master' }}
      uses: svenstaro/upload-release-action@master
      with:
        tag: v${{ env.VERSION }}
        file: linux.zip
          